const fs = require('fs');
const path = require('path');
const exec = require('child_process').exec;
const { assertInModule, extractModules, extractChunks } = require('./util');

const suite = [validateTest1, validateTest2];

function runSuite() {
    if (!suite.length) {
        console.log('SUCCESS');
    } else {
        const testCase = suite.shift();
        testCase(runSuite);
    }
}

function validateTest1(callback) {
    console.log('[Validate] test1');
    const output = path.resolve(__dirname, 'out/bundle1.js');

    const src = fs.readFileSync(output).toString();
    const modules = extractModules(src);
    // 0: Haxe entry point
    // 1: test.json

    assertInModule(0, modules[0], "Test1 Haxe module", [
        '// Generated by Haxe ',
        'var Test1 = function',
        'Test1.main()',
        'var json = __webpack_require__(1)' // require('./test.json')
    ]);

    assertInModule(1, modules[1], "Included `test.json` module", [
        'module.exports = {\\"answer\\":42}'
    ]);

    runOutput(output, callback);
}

function validateTest2(callback) {
    console.log('[Validate] test2');
    const output = path.resolve(__dirname, 'out/bundle2.js');
    const output2 = path.resolve(__dirname, 'out/0.bundle2.js');

    let src = fs.readFileSync(output).toString();
    let modules = extractModules(src);
    // 0: Haxe entry point

    assertInModule(0, modules[0], "Test2 Haxe module", [
        '// Generated by Haxe ',
        'var Test2 = function',
        'Test2.main()',
        'var Test2Sub', // host
        'Test2Sub = $s.Test2Sub' // bridge
    ]);

    src = fs.readFileSync(output2).toString();
    modules = extractModules(src);
    // 1: Haxe split bundle

    assertInModule(1, modules[1], "Test2Sub Haxe module", [
        'var Test2Sub = function',
        '$s.Test2Sub = Test2Sub' // export
    ]);

    runOutput(output, callback);
}

function runOutput(output, callback) {
    exec(`node ${output}`, (err, stdout, stderr) => {
        if (err) {
            console.log(stdout);
            console.log(stderr);
            throw `Failed to run ${output}`;
        }
        console.log(stdout);
        callback();
    });
}

runSuite();
