const fs = require('fs');
const path = require('path');
const { assertInModule, extractModules, extractChunks } = require('./util');

function run() {
    validateTest1();
    validateTest2();
    console.log('SUCCESS');

    // generate dummy index.html
    const bundles = ['bundle1', 'bundle2'];
    fs.writeFileSync(path.join(__dirname, 'www/index.html'),
        '<!DOCTYPE html>\n' + bundles.map(b => `<script src="${b}.js"></script>`).join('\n'));
}

function validateTest1() {
    console.log('[Validate] test1');

    const src = fs.readFileSync(path.resolve(__dirname, 'www/bundle1.js')).toString();
    const modules = extractModules(src);
    // 0: Haxe entry point
    // 1: detect global
    // 2: test.json

    assertInModule(modules[0], "Test1 Haxe module", [
        '// Generated by Haxe ',
        'var Test1 = function',
        'Test1.main()',
        'var json = __webpack_require__(2)' // require('./test.json')
    ]);

    assertInModule(modules[2], "Included `test.json` module", [
        'module.exports = {\\"answer\\":42}'
    ]);
}

function validateTest2() {
    console.log('[Validate] test2');

    let src = fs.readFileSync(path.resolve(__dirname, 'www/bundle2.js')).toString();
    let modules = extractModules(src);
    // 0: detect global
    // 1: Haxe entry point

    assertInModule(modules[1], "Test2 Haxe module", [
        '// Generated by Haxe ',
        'var Test2 = function',
        'Test2.main()',
        'var Test2Sub', // host
        'Test2Sub = $s.Test2Sub' // bridge
    ]);

    src = fs.readFileSync(path.resolve(__dirname, 'www/0.bundle2.js')).toString();
    modules = extractChunks(src);
    // 2: Haxe split bundle

    assertInModule(modules[2], "Test2Sub Haxe module", [
        'var Test2Sub = function',
        '$s.Test2Sub = Test2Sub' // export
    ]);
}

run();
